# Generated by Django 5.2.12 on 2026-03-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sensorreading',
            new_name='monitor_sen_fridge__c994fe_idx',
            old_name='monitor_sen_fridge__068f85_idx',
        ),
        migrations.RenameIndex(
            model_name='sensorreading',
            new_name='monitor_sen_timesta_37eabb_idx',
            old_name='monitor_sen_timesta_4e8385_idx',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='safety_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
