# Generated by Django 5.2.12 on 2026-04-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monitor",
            "0002_rename_monitor_sen_fridge__068f85_idx_monitor_sen_fridge__c994fe_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoredUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("fridge", "Fridge"),
                            ("freezer", "Freezer"),
                            ("fermentation_room", "Fermentation Room"),
                            ("wine_cooler", "Wine Cooler"),
                            ("dry_store", "Dry Store"),
                            ("blast_chiller", "Blast Chiller"),
                        ],
                        max_length=32,
                    ),
                ),
                ("unit_number", models.PositiveSmallIntegerField()),
                ("datasette_table", models.CharField(max_length=64, unique=True)),
                ("active", models.BooleanField(default=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["unit_type", "unit_number"],
                "unique_together": {("unit_type", "unit_number")},
            },
        ),
    ]
